### PR TITLE
Linked list

### PR DESCRIPTION
**Pull request by nks5295**
Solves issue #41.  Linked list is good to go.

### CODE REVIEW

**Comment by twood02** [comment]
I can't auto merge this because it's including a lot more commits than just your linked list.  Can you rebase or use some other magic to get rid of the unrelated stuff?

**Comment by twood02** [comment]
actually the issue is probably just with conflicts on the Makefile since #52 rewrote all of them.  In any case, you might as well clean it up.

**Comment by nks5295** [comment]
I don't really know why the commit messages are included in this... I did however pull and merge from the master so the Makefile issue is cleaned up.

**Comment by twood02** [comment]
looks good.

**Pull request merged**
