### PR TITLE
Created iplookup.c in sockets folder.

### PR DESCRIPTION
**Pull request by Chryel**
Worked on with Stephen Monaghan at @smonaghan. Using getaddrinfo, it is possible to find the primary IP address for a given hostname (assuming the hostname is entered correctly in command line). I'm not entirely too sure where to add a makefile, as sockets folder already contains a makefile for client-tcp/udp and server-tcp/udp. We're assuming as error checking should be implemented, so that will be added by tomorrow or Wednesday.

### CODE REVIEW

**Comment by twood02** [comment]
let's make it a bit more advanced--the program should be able to either return an IP from a hostname, or return a hostname from a given IP.  Since you get back the linked list, you might as well have it print out all of the information in the list, not just the first.

**Comment by Chryel** [comment]
I've updated iplookup.c to handle both types of inputs, those being IPv4 addresses and hostnames. The choices of inputs are handled by flags where -h flag dictates a hostname input and a -i flag dictates an IPv4 address input. I've also edited it so that searching for IPv4 address from hostname lists all found addresses.

**Comment by Chryel** [comment]
Some formatting issues, missing comments, and descriptions of input/output examples were added.

**Comment by twood02** [comment]
overall the code is pretty good.  You still have some formatting issues (tabs instead of spaces) and you should get used to using a better command line argument processing function like getopt.  I'm accepting this for now and we'll fix those small issues later.

**Pull request merged**
