### PR TITLE
Hashtable implementation

### LINKED ISSUE #42: Hash Table
Use the Linked List from #41 to create a chained hash table.

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Closes #42. Depends on #54

Also includes some cleanup of the `datastructs` directory to integrate additional structures

### CODE REVIEW

**Comment by twood02** [comment]
overall this looks very nice, but I've got conflicts because of #52 I think.  Update to the latest from this repo, clean up and resubmit.

**Comment by phil-lopreiato** [comment]
Master merged in. You should still merge #54  before this one, though

**Comment by twood02** [comment]
sorry to do this to you again, but it looks like merging #54 caused a new conflict for you...  try try again!

**Comment by phil-lopreiato** [comment]
@twood02 all better

**Comment by twood02** [comment]
nice!

**Pull request merged**
