### PR TITLE
Completed Timer/Histogram Utility

### PR DESCRIPTION
**Pull request by Chryel**
As mentioned in https://github.com/gwAdvNet2015/gw-kv-store/issues/34.
I will be making an edit shortly to fix some formatting issues with certain files.

### CODE REVIEW

**Comment by twood02** [comment]
@Chryel -- I'm assuming you guys will also PR this into the gw-kv repo.

**Comment by phil-lopreiato** [comment]
@twood02 this was added in https://github.com/gwAdvNet2015/gw-kv-store/commit/8907b9e8bea98d413d7b8e4f3db104d8d1295d1e

**Comment by twood02** [comment]
@Chryel - Does this version have any fixes that had to be made for the gw-kv version?  Is it ready for me to merge this here?

**Comment by Chryel** [comment]
The version for adv-net-samples is up to date. I just migrated the files to the gw-kv repo from here.

**Comment by twood02** [comment]
ok, I've merged with adv-net-samples

**Pull request merged**
