### PR TITLE
Issue # 2 RingBuffer Data Structure  

### PR DESCRIPTION
**Pull request by huyang1988**

### CODE REVIEW

**Comment by twood02** [comment]
Oops. I already merged the code from #30 -- are there any differences between it and this?

**Comment by huyang1988** [comment]
It is a version to store 'int' data to a buffer because I don't think to store a 'void*' as a data is what we need. Besides, this is our design, while another one is not that consistent because Wenhui add something that was not in our design such as the IsEmpty() function. I think she was a little bit misunderstanding our design, and uploaded code before we decided.

**Comment by huyang1988** [comment]
By the way, it is my first time to use github, so I asked her to do the upload part before. However, since we have some different opinions, she told me to upload another copy of this code.

**Comment by wenhuizhang** [comment]
Good afternoon: 

Personally we had some different opinions over the requirement of the Issue, so we decided to upload two versions at the same time instead of switching from one version to the other, that makes the situation confusing. 

The arguing point is whether we should keep the void\* type in the issue or to change it to a int , which does not make sense to me personally. My personal understanding of a homework is that answering the question yet not questioning and changing the requirement of the homework. 

Thanks, 

Wenhui

**Pull request closed without merging**
