### PR TITLE
Timer utility attempt #1

### PR DESCRIPTION
**Pull request by Chryel**
For now, we created a simple doubly linked list to keep track of timers' records. This is in place instead of a histogram at this point. Due to some bad planning on my end, the structure is a bit weird, but that will be rectified later on once functionality is established. Issue #12. Worked on with @SMonaghan.

### CODE REVIEW

**Comment by twood02** [comment]
A linked list is a great way of keeping track of data when you are adding / removing items in the middle of it.  For our timers however, your focus should just be on efficiently being able to report the time of a measurement.  Don't worry about recording all of the data (in a list / array / anything else) --- you can still report an average just by maintaining a running sum of values!

See if you can make your timers work without storing all the values.  Later once we have a histogram data structure we can add that as a way to store an _approximation_ of all the values (i.e., we just store a count of how many fall into certain buckets, taking up much less space than all of the data).

Make sense?

**Comment by Chryel** [comment]
I've removed all the un-needed structs like the linked list. The timer struct holds information for minimum, maximum, number of times used. The current minimums and maximums are determined at the end of the timer measurement. The program has a statically set 10 limit, but can be changed later to support a dynamic limit.

**Comment by twood02** [comment]
The logic in your code looks fine.  Can you add a test case program which demonstrates how to use the counter?  Have it measure the time for processing a few different meaningless loops or operations and then print out each value and the max/min/avg.

Also check your formatting--you need a lot more spaces to match the style guide's indentation requirements.

**Comment by Chryel** [comment]
Hey Tim,

We're having some trouble with variables not storing values correctly or something close to that. I hope you don't mind if we ask you questions tomorrow.

**Comment by twood02** [comment]
That's fine--this will tie in with what we are doing in class today.

**Pull request merged**
