### PR TITLE
Issue #10 Adding multi-threaded bandwidth tester and updated makefile for it

### PR DESCRIPTION
**Pull request by nks5295**
This closes issue #10.  It is the client-tcp.c file with added options to open multiple sockets in their own thread, send specified amount of packets, output total packets sent every x seconds, and you can change the delay between packet sends.

The Makefile has an option to compile this program.

### CODE REVIEW

**Comment by twood02** [comment]
Code looks good.  Can you add a comment here that shows some output from the program, preferably connecting to some local server (high bandwidth) and some distant server (lower bandwidth)?

**Comment by nks5295** [comment]
- Local server (High Bandwidth):
  ➜  bandwidth git:(master) ✗ time ./multi-bandwidth-test -n 100 -t 3 -x 1
  Sending 100 packets
  Connecting to 127.0.0.1:1234
  Creating 3 worker threads
  New thread created with id 255975424
  New thread created with id 256512000
  New thread created with id 257048576
  [255975424] Sending complete!
  [257048576] Sending complete!
  [256512000] Sending complete!
  Done -- sent 303 packets.
  ./multi-bandwidth-test -n 100 -t 3 -x 1  0.00s user 0.00s system 85% cpu 0.006 total
- Offsite server (Low bandwidth):
  ➜  bandwidth git:(master) ✗ time ./multi-bandwidth-test -p 20012 -h teehee.me -n 100 -t 3 -x 1
  Sending 100 packets
  Connecting to teehee.me:20012
  Creating 3 worker threads
  New thread created with id 2826240
  New thread created with id 3362816
  New thread created with id 3899392
  [3899392] Sending complete!
  [3362816] Sending complete!
  [2826240] Sending complete!
  Done -- sent 303 packets.
  ./multi-bandwidth-test -p 20012 -h teehee.me -n 100 -t 3 -x 1  0.00s user 0.00s system 12% cpu 0.037 total

@atryus's server is running on Google Fiber so he does not have a significant bottleneck to effect the speed :p

**Comment by twood02** [comment]
OK, looks good!  Later we will add more statistics to show information like the send rate achieved, but this is fine for now.

**Comment by twood02** [comment]
@nks5295 @phil-lopreiato what am I supposed to run as the server to use your bandwidth tester?

**Comment by phil-lopreiato** [comment]
You can run the code from #24.

So in `threads/`, run `make server-tcp && ./server-tcp`

**Pull request merged**
